# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HabitPromiss' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'Charts'
  pod 'FSCalendar'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRealm'
  # Pods for HabitPromiss

  target 'HabitPromissTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HabitPromissUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
